// react-micro-app/src/App.js
import { HashRouter as Router, Switch, Route, Link } from 'react-router-dom'
import logo from './logo.svg'
import './App.css'

const Home = () => <h1 className="home-text">This Is Home Page!!!</h1>
const About = () => <h1 className="about-text">This Is About Page!!!</h1>

function App() {
  return (
    <Router>
      <div className="App">

        <h1>react-micro-app 子应用</h1>

        {/* 导航 */}
        <nav style={{ margin: 20 }}>
          <Link to="/">Home</Link>
          <span style={{ margin: 10 }}>|</span>
          <Link to="/about">About</Link>
        </nav>

        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
        </header>

        {/* 匹配的路由 */}
        <Switch>
          <Route path="/" exact>
            <Home />
          </Route>
          <Route path="/about" exact>
            <About />
          </Route>
        </Switch>
      </div>
    </Router>
  )
}

export default App

// vue3-micro-app/src/App.vue
<template>
  <h1>vue3-micro-app 子应用</h1>
  <nav>
    <router-link to="/">Home</router-link>
    |
    <router-link to="/about">About</router-link>
  </nav>

  <div>
    <img alt="Vue logo" src="./assets/logo.png" />
    <router-view />
  </div>
</template>

<style lang="scss">
#micro-vue-app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
}

nav {
  padding: 30px;

  a {
    font-weight: bold;
    color: #2c3e50;
    margin: 0 10px;
    &.router-link-exact-active {
      color: #42b983;
    }
  }
}
</style>
